# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

tests:
  cache:
    paths:
      - cargo/
      - target/
  script:
    - rustup override add nightly
    - rustc --version && cargo --version      # Print version info for debugging
    - cargo fmt -- --check
    - cargo test --release --all --verbose

# TODO clippy