# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# clippy doesn't play well with caching for some reason
#variables:
#  CARGO_HOME: $CI_PROJECT_DIR/cargo

tests:
  #cache:
  #  paths:
  #    - cargo/
  #    - target/
  script:
    - rustup override add nightly
    - rustc --version && cargo --version  # Print version info for debugging
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview
    - cargo fmt -- --check
    - cargo clippy -- --deny warnings
    - cargo test --release --all --verbose
    - cargo bench --verbose  # make sure benches compile
