# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Use cargo to test the project
tests:
  script:
  - rustup override add nightly
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --release --all --verbose

# TODO clippy
# TODO fmt